buger/jsonparser

- parser.go
- parser_test.go
There was a typo in `getBoolean` causing a runtime panic. I've added some tests to cover that function.
> Fix typo causing runtime panic in getBoolean

- README.md
- parser.go
- parser_test.go
* Added `GetString` method which does proper unicode and escape symbols handling. Note that it will cause additional memory allocations. Currently it use built-in go function, but i guess its not really fast.
* All `Get[Type]` function now return only 2 arguments, value and error.
* `UnsafeBytesToString` now public function, and added docs how to use it.
> Support for unicode and escaped symbols and some API changes

- parser.go
Improved `stringEnd` performance by handling the escaped/unescaped state on every iteration, but instead backtracking from each double quote found and counting the number of preceding backslashes. This sounds more expensive, but it optimizes for the overwhelmingly common case that there is only one double quote (the end quote).
<TODO>
<TODO>
> Improve performance of PR #21

- parser_test.go
Before, when the value returned by Get() doesn't match the expected output, the error message printed would dump byte arrays to the screen.
Now, they are cast to strings before printing for human readability.
> Made failing tests print more human-readable errors

- parser.go
- parser_test.go
Made a new type, `ValueType`, which is now used everywhere for `dataType` in place of `int`. This seems more Go idiomatic and also type-safer (no accidental confusion with the `offset` return, for instance). Requires minor changes to code that calls into this library.
> Using new ValueType instead of int for dataType

- parser.go
- parser_test.go
This PR exports some errors as global variables to easier check for errors when calling Get* methods.
For now I exported just two errors, key path not found and unknown value type. If you think this type of error management is good I can change it also for other errors where it would make sense.
`enchmarkJsonParserLarge-8 	  100000	     73036 ns/op	      32 B/op	       2 allocs/op`
`BenchmarkJsonParserMedium-8	  500000	     12253 ns/op	      32 B/op	       2 allocs/op`
`BenchmarkJsonParserSmall-8 	 5000000	      1217 ns/op	       0 B/op	       0 allocs/op`
`BenchmarkJsonParserLarge-8 	  100000	     74244 ns/op	       0 B/op	       0 allocs/op`
`BenchmarkJsonParserMedium-8	  500000	     12597 ns/op	       0 B/op …
> Better error handling

- parser_test.go
Just added a few more test cases (they all pass, though they demonstrate that a key/value may be matched in mildly-malformed JSON sometimes).
> Added a few more tests for corner cases

- fastbytes.go
- fastbytes_test.go
- fastbytessafe.go
- fastbytesunsafe.go
- fastbytesunsafe_test.go
- parser.go
Pardon the unhelpful PR title; wasn't sure what to call this...
Removed the `unsafeBytesToString` function, instead encapsulating `unsafe` functionality in a separate set of files (`fastbytes*`), thus preventing misuse by client code. Included are fast implementations of `BytesEqualStr`, which takes one string and one []byte argument, and `BytesParseFloat` and `BytesParseInt`, which each take a `[]byte` argument. None of these functions let unsafe strings escape, thus improving overall safety.
The main benefit of this refactoring is the ability to have non-unsafe fallback versions of these functions for platforms without the `unsafe` package (such as Google App Engine). Such implementations are included in `fastbytessafe.go`.
A somewhat faster implementation of BytesEqualStr is included …
> Faster+safer use of unsafe package + non-unsafe fallback implementations

- bytes_safe.go
- bytes_unsafe.go
- escape.go
- escape_test.go
- parser.go
- parser_test.go
Added proper JSON escaped string handling in both keys and values (as per [RFC 7159](https://tools.ietf.org/html/rfc7159)). These changes necessarily resulted in some performance degradation, but it's relatively minor (< 10%, it seems).
(Note: this is a refinement of #39)
*Benchmark before:*
```
BenchmarkJsonParserLarge-8 	 	     64506 ns/op	       0 allocs/op
BenchmarkJsonParserMedium-8	 	     10865 ns/op	       0 allocs/op
BenchmarkJsonParserSmall-8 		      1026 ns/op	       0 allocs/op
```
*Benchmark after:*
```
BenchmarkJsonParserLarge-8 	  	     66558 ns/op	       0 allocs/op
BenchmarkJsonParserMedium-8	 	     11958 ns/op	       0 allocs/op
BenchmarkJsonParserSmall-8 		      1061 ns/op	       0 allocs/op
```
> Handle escaped keys and values in JSON

- parser.go
- parser_test.go
This PR depends on PR #40; please merge before considering this one.
Adds `ParseBoolean`, `ParseString`, and `ParseNumber` to assist users in efficiently decoding the raw bytes for each of these `ValueType`s into the equivalent Go value. All assume that the value bytes passed in were produced by `Get()`, `ArrayEach()`, or some other `jsonparser` getter, and have been validated to the extent those functions do validation.
There is also a `ParseStringAsBytes` that functions the same as `ParseString` (see below) but skips the final conversion to `string` type, returning a `[]byte` instead (slightly more efficient if the user needs unescaping but not a `string`).
`ParseBoolean` simply checks if the first byte is `'t'`; this is trivial but is included for completeness. Returns only a `bool` …
> Added ParsePrimitiveValue convenience function for users

- parser.go
The only significant change is that `ParseBoolean` is now more robust; it won't panic on an empty byte slice input and it will reject strings like `"trux"` and `"foo"` with an error. While this does repeat the validation done by `Get()`, the `Parse*` functions aren't really performance-critical code and this makes things safer.
> Minor cleanups/fixes for the new Parse functions

- parser_test.go
Note: this PR can be merged on its own without conflict, but some tests for `ParseBoolean` will fail until the more robust implementation from PR #46 is merged.
> Improved test code and added Parse* tests

- Makefile
- benchmark/benchmark_medium_payload_test.go
- benchmark/benchmark_small_payload_test.go
- parser.go
- parser_test.go
Fetch multiple keys at once. Instead of reading whole payload for each key, it does read only 1 time.
Using new API you can get nearly 2x improvement when fetching multiple keys, and the more keys you fetch, the bigger difference. 
Example:
```go
paths := [][]string{
[]string{"uuid"},
[]string{"tz"},
[]string{"ua"},
[]string{"st"},
}
jsonparser.EachKey(smallFixture, func(idx int, value []byte, vt jsonparser.ValueType, err error){
switch idx {
case 0: // uuid
// jsonparser.ParseString(value)
case 1: // tz
jsonparser.ParseInt(value)
case 2: // ua
// jsonparser.ParseString(value)
case 3: //sa
jsonparser.ParseInt(value)
}
}, paths...)
```
```
BenchmarkJsonParserLarge 	  100000	     84621 ns/op	       0 B/op	       0 allocs/op …
```
> Add EachKey

- escape.go
- parser_test.go
Fixes #49 and adds tests to actually test escaped whitespace in keys/values.
> Fixed some two-character escapes like \n not escaping right

- parser.go
- parser_test.go
Fixed an infinite loop in `searchKeys` in the presence of an unclose JSON array. There may be similar bug(s) in `KeyEach`, maybe you can check @buger?
> Bugfix searchKeys for malformed JSON arrays

- parser_test.go
Makes tests more effective by differentiating between key not found and error cases.
> Tests distinguish between error and key-not-found

- benchmark/benchmark_medium_payload_test.go
- benchmark/benchmark_small_payload_test.go
- parser.go
- parser_test.go
This PR implements the `ObjectEach` function to iterate over the key-value pairs of a JSON object. Its signature is as follows:
```
ObjectEach(
data []byte,
callback func(key []byte, value []byte, valueType ValueType, offset int) error,
)
```
`ObjectEach` will invoke `callback` for each key-value pair in the JSON object contained in `data` as follows:
* `key` will be the _unescaped_ key string of the key-value pair
* `value` will be the raw bytes composing the value of the key-value pair (as if returned by `Get()`; quotes are stripped from strings, `null` is represented as an empty byte slice, and all other values are passed as their literal bytes)
* `valueType` is the JSON data type of `value`
* `offset` is the byte offset just past the end of the value of the key-value pair
If any …
> Add ObjectEach() for iterating over object key-value pairs

- parser.go
- parser_test.go
**Description**: This fixes the problem that calling Get on simple values would fail:
```go
data := []byte("0")
value, dataType, offset, err := Get(data)
// err == "Value looks like Number/Boolean/None, but can't find its end: ',' or '}' symbol"
```
```
BenchmarkJsonParserLarge-4                    	  100000	     88822 ns/op	       0 B/op	       0 allocs/op
BenchmarkJsonParserMedium-4                   	  500000	     13879 ns/op	       0 B/op	       0 allocs/op
BenchmarkJsonParserEachKeyManualMedium-4      	 1000000	      7999 ns/op	       0 B/op	       0 allocs/op
BenchmarkJsonParserEachKeyStructMedium-4      	 1000000	      8586 ns/op	     544 B/op	      11 allocs/op
BenchmarkJsonParserObjectEachStructMedium-4   	  500000	     14922 ns/op	     608 B/op …
```
> Fix parsing of values

- README.md
- parser.go
- parser_test.go
Now you can use array indexes as keys: `jsonparser.GetInt("person", "avatars", "[0]", "url”)`
And it even works when you want to extract multiple keys using `EachKey`.
> Add support for array idx keys

- README.md
**Description**: Fixes a typo in `README` file.
> No changes.
> No changes.
> docs(readme): fix EachKey method name typo

- parser.go
fixes issue #83 
With this implementation it no longer makes sense to pass err to the callback function, since in the event of a parse error from get the cb function does not get called anymore.
Then again since the cb function is unable to propagate the error anyway (issue #53 ) the whole way errors in the cb function are handled seems odd to me, but this is debatable ofcourse.
> added fix for issue #83

- .travis.yml
- parser.go
- parser_test.go
Reopen PR #86
ArrayEach() correctly parse empty array, or with whitespace (#79)
Change golang version on travis ci to 1.7 (need for testing method `t.Run()`)
```
BenchmarkJsonParserLarge-4                    	  100000	     66302 ns/op	       0 B/op	       0 allocs/op
BenchmarkJsonParserMedium-4                   	 1000000	     10059 ns/op	       0 B/op	       0 allocs/op
BenchmarkJsonParserEachKeyManualMedium-4      	 1000000	      6535 ns/op	     112 B/op	       2 allocs/op
BenchmarkJsonParserEachKeyStructMedium-4      	 1000000	      6987 ns/op	     656 B/op	      13 allocs/op
BenchmarkJsonParserObjectEachStructMedium-4   	 1000000	     10135 ns/op	     608 B/op	      12 allocs/op
BenchmarkJsonParserSmall-4 …
```
> fix #79 - allow empty array in ArrayEach

- parser.go
- parser_test.go
Fix issue #81 
Previously offset from nested searchKeys call was added to parent value such that 11 + (-1) would return a "successful" value of 10. I added logic to read the value of the nested call and return a failure as needed.
BenchmarkJsonParserLarge-8                        200000             44154 ns/op               0 B/op          0 allocs/op
BenchmarkJsonParserMedium-8                      1000000              7197 ns/op               0 B/op          0 allocs/op
BenchmarkJsonParserEachKeyManualMedium-8         2000000              4168 ns/op             112 B/op          2 allocs/op
BenchmarkJsonParserEachKeyStructMedium-8         2000000              4527 ns/op             656 B/op         13 allocs/op …
> Bugfix recursive object index

- benchmark/benchmark_large_payload_test.go
- benchmark/benchmark_medium_payload_test.go
- benchmark/benchmark_small_payload_test.go
Benchmark results running on my machine. 
__Small payload:__
```
Jason                      	  500000	     19378 ns/op	    7237 B/op	     101 allocs/op
GoSimplejson               	 1000000	     10394 ns/op	    2241 B/op	      36 allocs/op
EncodingJsonStruct         	 1000000	      6645 ns/op	     896 B/op	      18 allocs/op
EncodingJsonInterface      	 1000000	      6835 ns/op	    1521 B/op	      38 allocs/op
Gabs                       	 1000000	      8909 ns/op	    1649 B/op	      46 allocs/op
Ugirji                     	 1000000	      6061 ns/op	    2192 B/op	      31 allocs/op
Ujson                      	 1000000	      5005 ns/op	    1409 B/op	      37 allocs/op
Djson                      	 2000000	      3862 ns/op	    1249 B/op	      30 allocs/op
FFJson                     	 2000000 …
```
> bench: add a8m/djson as a compared library #75

- escape.go
- escape_test.go
- parser.go
- parser_test.go
When escaping characters in the upper part (`]\uDFFF-\uFFFF[`) of the Basic Multilingual Plane (BMP), the `decodeUnicodeEscape` would fail to see that this was a single rune instead of complex UTF16 rune.
When checking for single rune we now check if correctly if the single rune is within the complete space of BMP `[\u0000-\uFFFF[` and that its not in `[\uD800-uDFFF]`.
Furthermore I've fixed a bug in ParseString, such that if a unescape error happens a `MalformedValueError` is returned. I've also added unit test for ParseString.
NB: To run the benchmarks in the docker container i changed the Dockerfile to use `golang:1.8` instead of `golang:1.6`.
BenchmarkJsonParserLarge-4                    	  200000	     58070 ns/op	       0 B/op	       0 …
> Bugfix: Characters in upper part of BMP would fail unescaping

- parser.go
This error needs to be handled otherwise we can put string value in between [] while fetching array elements.
This error needs to be handled for cases like 
`jsonparser.Get(data, "array", [random]) //square brackets will take string in between`
For running benchmarks use:
```
go test -test.benchmem -bench JsonParser ./benchmark/ -benchtime 5s -v
make bench (runs inside docker)
```
> error handling while calling strconv.Atoi() while getting array element by index

- parser.go
- parser_test.go
This PR fixes bug where this test fails due to quotes being stripped prematurely from string, resulting in `UnknownValueTypeError`.
```
desc:    "get string from array",
json:    `{"a":[{"b":1},"foo", 3],"c":{"c":[1,2]}}`,
path:    []string{"a", "[1]"},
isFound: true,
data:    "foo",
```
This is due to `searchKeys()` calling `ArrayEach()` to look up the index match, which calls `Get()`, which strips quotes from strings, resulting in `valueFound` pointing to string contents without quotes, which then looks like an unknown value type.
There may be a better suggested fix than the one I did (like just updating the offset directly in the slice), open to suggestions.
> Bugfix: Get() via index fails on string

- parser.go
This PR removes the special case for when `null` is found by `Get()`. Previously, a new, empty slice was allocated to return (via `[]byte{}`), which allocates memory (abeit a very small amount) and gives `null` a special behavior (as opposed to `true` and `false`, which return a byte slice containing the literal keyword. Let's just leave the return as the bytes `null`, instead.
> Removed special handling of 'null' value return

- README.md
- benchmark/benchmark_small_payload_test.go
- parser.go
- parser_test.go
This PR adds support for `Set` method, enabling end users to use jsonparser to generate json efficiently.
_Note: I am taking this over from #98 after discussion with @ryanleary as he does not have cycles to complete it at the moment._
```
BenchmarkJsonParserLarge-4                         50000            170465 ns/op               0 B/op          0 allocs/op
BenchmarkJsonParserMedium-4                       200000             29789 ns/op               0 B/op          0 allocs/op
BenchmarkJsonParserEachKeyManualMedium-4          500000             18119 ns/op             112 B/op          2 allocs/op
BenchmarkJsonParserEachKeyStructMedium-4          500000             21547 ns/op             656 B/op         13 allocs/op …
```
> Add initial Set implementation #61

- .gitignore
- README.md
- benchmark/benchmark_medium_payload_test.go
- benchmark/benchmark_small_payload_test.go
- bytes_safe.go
- bytes_unsafe.go
- bytes_unsafe_test.go
- parser.go
- parser_test.go
This pull request adds a delete method to jsonparser, allowing users to remove json at a given path.
```
BenchmarkJsonParserLarge-4                    	  100000	     73291 ns/op	     752 B/op	      94 allocs/op
BenchmarkJsonParserMedium-4                   	  500000	     12786 ns/op	      40 B/op	       5 allocs/op
BenchmarkJsonParserEachKeyManualMedium-4      	 1000000	      7033 ns/op	     120 B/op	       3 allocs/op
BenchmarkJsonParserEachKeyStructMedium-4      	 1000000	      7535 ns/op	     672 B/op	      12 allocs/op
BenchmarkJsonParserObjectEachStructMedium-4   	  500000	     11908 ns/op	     664 B/op	      16 allocs/op
BenchmarkJsonParserSmall-4                    	10000000	      1179 ns/op	      32 B/op	       4 allocs/op …
```
> Add delete implementation

- README.md
**Description**: Fixed example and response type for `GetInt`.
**Benchmark before change**: N/A
**Benchmark after change**: N/A
> Fixed GetInt docs

- parser.go
- parser_test.go
**Description**: fix Delete() method #123
```
BenchmarkJsonParserLarge-4                    	  200000	     49941 ns/op	       0 B/op	       0 allocs/op
BenchmarkJsonParserMedium-4                   	 1000000	      7363 ns/op	       0 B/op	       0 allocs/op
BenchmarkJsonParserDeleteMedium-4             	 1000000	      6219 ns/op	       0 B/op	       0 allocs/op
BenchmarkJsonParserEachKeyManualMedium-4      	 1000000	      5056 ns/op	     112 B/op	       2 allocs/op
BenchmarkJsonParserEachKeyStructMedium-4      	 1000000	      5781 ns/op	     672 B/op	      12 allocs/op
BenchmarkJsonParserObjectEachStructMedium-4   	 1000000	      8082 ns/op	     624 B/op	      11 allocs/op
BenchmarkJsonParserSmall-4                    	10000000	       784 ns/op	       0 B/op …
```
> Fix Delete()

- parser.go
- parser_test.go
Right now when last item in object is deleted, trailing commas remain and make json invalid.
For example: 
Given such a json: 
```{ "a": "1", "b": "2"}```
If we delete `b` key then the result will be: 
```{ "a": "1",}```
This makes json invalid. In this PR I've fixed it.
```
BenchmarkJsonParserLarge-4                        100000             69483 ns/op               0 B/op          0 allocs/op
BenchmarkJsonParserMedium-4                      1000000             11553 ns/op               0 B/op          0 allocs/op
BenchmarkJsonParserDeleteMedium-4                 500000             11788 ns/op               0 B/op          0 allocs/op
BenchmarkJsonParserEachKeyManualMedium-4         1000000              7436 ns/op             112 B/op …
```
> Trailing commas should be removed when last item in the object is deleted

- parser.go
- parser_test.go
Closes #117. You can now use `Set` with array indices when the full path does not already exist.
```
BenchmarkJsonParserLarge-4                    	  100000	     75566 ns/op	       0 B/op	       0 allocs/op
BenchmarkJsonParserMedium-4                   	  500000	     13141 ns/op	       0 B/op	       0 allocs/op
BenchmarkJsonParserDeleteMedium-4             	 1000000	     10421 ns/op	       0 B/op	       0 allocs/op
BenchmarkJsonParserEachKeyManualMedium-4      	 1000000	      7995 ns/op	     112 B/op	       2 allocs/op
BenchmarkJsonParserEachKeyStructMedium-4      	 1000000	      8653 ns/op	     672 B/op	      12 allocs/op
BenchmarkJsonParserObjectEachStructMedium-4   	  500000	     12323 ns/op	     624 B/op	      11 allocs/op …
```
> Add additional support for array indexing in Set

- parser.go
- parser_test.go
This change makes sure `{"a": "1" ,"b": "2" }` does not end up as `{ ,"b": "2" }`, but as `{"b": "2" }`, when deleting `b`.
I didn't dig too deep into the code, so I could be tackling this at the wrong layer, but this solved the specific issue I am seeing, and it keeps other tests from failing.
Unfortunately I am unable to get the benchmark tests running locally, with or without Docker. Both cases are blocked on – I assume – a lack of version pinning:
```shell
$ docker build -t jsonparser .
Sending build context to Docker daemon  832.5kB
Step 1/10 : FROM golang:1.6
---> 63330314bb46
Step 2/10 : RUN go get github.com/Jeffail/gabs
---> Running in 097509d47196
src/github.com/Jeffail/gabs/gabs.go:486: e.SetEscapeHTML undefined (type *json.Encoder has no field or method SetEscapeHTML) …
```
> Correctly handle space-comma case in Delete

- parser.go
- parser_test.go
This Pr fixes the bug of **Get**  function where nested values return the wrong result of some other parent key [because of the same nestinglevel].
```
goos: darwin
goarch: amd64
pkg: github.com/soniabhishek/jsonparser/benchmark
BenchmarkJsonParserLarge-4                        100000             60877 ns/op               0 B/op          0 allocs/op
BenchmarkJsonParserMedium-4                      1000000              9819 ns/op               0 B/op          0 allocs/op
BenchmarkJsonParserDeleteMedium-4                1000000             10166 ns/op               0 B/op          0 allocs/op
BenchmarkJsonParserEachKeyManualMedium-4         1000000              6054 ns/op             112 B/op          2 allocs/op …
```
> Fixing the issue of wrong get value

- parser.go
My benchmarking showed that this array was actually leaking to the heap. Narrowing its scope in the hope of it not escaping, but also limiting its allocation only to cases where it is actually required.
Improve the performance of the `ObjectEach` API by preventing it from allocating unnecessarily.
> Only allocate array if required

- parser.go
- parser_test.go
**Description**: This PR is to address the open issue: https://github.com/buger/jsonparser/issues/164
goos: darwin
goarch: amd64
pkg: github.com/buger/jsonparser/benchmark
BenchmarkJsonParserLarge-8                        200000             49082 ns/op               0 B/op          0 allocs/op
BenchmarkJsonParserMedium-8                      1000000              7254 ns/op               0 B/op          0 allocs/op
BenchmarkJsonParserDeleteMedium-8                1000000              7638 ns/op               0 B/op          0 allocs/op
BenchmarkJsonParserEachKeyManualMedium-8         1000000              5123 ns/op             112 B/op          2 allocs/op
BenchmarkJsonParserEachKeyStructMedium-8         1000000              5726 ns/op             544 B/op …
> Prevent infinite looping in GetString on certain malformed strings

- go.mod
- parser.go
- parser_test.go
If you are trying to extract "foo" and "foo.bar" from '{"foo": {"bar": 1}}' with EachKey, the parser would find the "foo" key, extract the contents ('{"bar": 1}'), and then *add the offset* of
that extraction to the current index. This means it would never find the "bar" key. This change simply eliminates the adding of the offset.
This appears to fix #174 and includes a test for it.
Benchmarks are broken.
> Attempt to fix #174, EachKey missing nested extractions

- parser.go
- parser_test.go
**Description**: This pr fix issue #188. If `findKeyStart` meets a `[` or `{`, it should not add i with `blockEnd`’s return value directly because it may return -1 if it did not find the close symbol
> fix issue 188

- parser.go
- parser_test.go
`Get()` and `EachKey()` will panic dealing with invalid parameters in some cases because of array out of bounds. This pr try to fix #177 and #178
> fix issue #177 #178

- benchmark/go.mod
- parser.go
- parser_test.go
If you try to set an unknown key, simple object within a nested array, passing in the index, the parser will override the object and does not take into account the given index [1].
With current parser version, given this json as input:
```json
{
"test": {
"key": [
{
"innerKey": "innerKeyValue",
"innerKey2": "innerKeyValue2"
}
]
}
}
```
and following path to set an unknown key: `"test", "key", "[1]", "newInnerKey"` with data `"new object"`, the output would be:
```json
{
"test": {
"key": [
{
"newInnerKey": "new object"
}
]
}
}
```
which I think it is wrong, since it overrides what index [0] had but the above path wanted to insert the object in index [1] instead.
With the changes done in this PR, given the same json input, path and data, the output would be:
```json
{
"test": {
"key": [
{ …
```
> Attempt to fix #185 - Set overrides items

- parser.go
- parser_test.go
**Description**: This PR fix issue #165. Since the use of `bytesToString` hack, `stackbuf` can't be reused to save the unescape result of the key. It will make the `pathsBuf`'s string element point to the same memory area if the path has more than one key which need to be unescaped. And that will make the `EachKey` can't not locate the key correctly.
> fix issue #165

- parser.go
- parser_test.go
**Description**: Fixed an infinite loop in `Get` (more precisely in `searchKeys`), when there is an opening brace instead of a closing and no key.
```
goos: darwin
goarch: amd64
pkg: benchmarks
BenchmarkJsonParserLarge-12                               126344             45841 ns/op               0 B/op          0 allocs/op
BenchmarkJsonParserMedium-12                              721712              7623 ns/op               0 B/op          0 allocs/op
BenchmarkJsonParserDeleteMedium-12                        681780              8168 ns/op               0 B/op          0 allocs/op
BenchmarkJsonParserEachKeyManualMedium-12                 919440              5554 ns/op             112 B/op          2 allocs/op
BenchmarkJsonParserEachKeyStructMedium-12 …
```
> Fix infinite loop in Get

- oss-fuzz-build.sh
**Description**: This PR moves over the build script of the fuzzers from oss-fuzz to jsonparsers own repo. This is recommended by Google to allow maintainers to easier update the build of the fuzzers in case of adding new fuzzers or the build breaking.
When merged in, I will update the integration at oss-fuzz to run the build script from here.
**Benchmark**: This PR does not change the performance of the core functionality.
> Added oss-fuzz build script

- bytes_unsafe.go
I found an incorrect cast from `string` to `[]byte` in `bytes_unsafe.go`. The problem is that when `reflect.SliceHeader` is created as a composite literal (instead of deriving it from an actual slice by cast), then the Go garbage collector will not treat its `Data` field as a reference. If the GC runs just between creating the `SliceHeader` and casting it into the final, real `[]byte` slice, then the underlying data might have been collected already, effectively making the returned `[]byte` slice a dangling pointer.
This has a low probability to occur, but projects that import this library might still use it in a code path that gets executed a lot, thus increasing the probability to happen. Depending on the memory layout at the time of the GC run, this could potentially …
> Fix possible memory confusion in unsafe slice cast

- go.mod
- parser.go
- parser_error_test.go
Per #56, EachKey cannot handle a variety of cases where there are more than 64 keys, or 64 elements in an array we're extracting. This fixes that.
Note that the PR template's command for running benchmarks (`go test -test.benchmem -bench JsonParser ./benchmark/ -benchtime 5s -v`) doesn't work, so I instead added a replace directive in the benchmark/ directory's go.mod to point at my checked-out repository, then ran `go test -bench .` against the master branch, then against my branch.
```
goos: linux
goarch: amd64
pkg: benchmarks
BenchmarkDeleteSmall-16                         	 1890744	       622 ns/op	     256 B/op	       3 allocs/op
BenchmarkDeleteNested-16                        	 2652386	       445 ns/op	     160 B/op …
```
> Eachkey fix

- parser.go
- parser_test.go
**Description**: This PR fixes a bug where repeated path matches incorrectly increment the data offset. Existing unit tests were modified and failed before applying the fix.
> Fixed repeated paths from incorrectly incrementing data offset.

- parser.go
This PR reduces unnecessary array allocations in `EachKey` function.
In our application, we heavily use `EachKey` to traverse moderately big JSON objects and our benchmarks showed that this would reduce allocation up to 55%:
```
name                       old time/op    new time/op    delta
ParseRequest-8    84.7µs ± 2%    76.7µs ± 2%   -9.47%  (p=0.000 n=9+10)
name                       old alloc/op   new alloc/op   delta
ParseRequest-8    20.7kB ± 0%     9.3kB ± 0%  -55.15%  (p=0.000 n=10+10)
name                       old allocs/op  new allocs/op  delta
ParseRequest-8       370 ± 0%       192 ± 0%  -48.11%  (p=0.000 n=10+10)
```
```BenchmarkJsonParserLarge
BenchmarkJsonParserLarge-8                        127772 …
```
> EachKey: do not allocate array if there is no need

- oss-fuzz-build.sh
> Update to use built-in fuzz function

- benchmark/benchmark_set_test.go
- parser.go
This pr improve the `Set` performance as #107 mentions.With large key path and set value, it brings an about 20% improvement.
Before:
```
goos: linux
goarch: amd64
pkg: github.com/buger/jsonparser
BenchmarkSetLarge-4   	    1000	   1002014 ns/op	 1611185 B/op	      15 allocs/op
```
After:
```
goos: linux
goarch: amd64
pkg: github.com/buger/jsonparser
BenchmarkSetLarge-4   	    1278	    791653 ns/op	 1232897 B/op	       4 allocs/op
```
> improve Set performance as #issue107 descripes

- parser.go
- parser_test.go
Attempt to fix #219 and introduce a test.  The only error that can easily be returned in this case is `KeyPathNotFoundError`, which is reasonable if you squint (a malformed key can not be found).
Note I'm far from fluent in golang so this should be reviewed with some care :smile:
> Cve 2020 35381

- .travis.yml
**Description**: Changed versions to be checked by TravisCI. This should fix #224.
```none
goos: linux
goarch: amd64
pkg: benchmarks
BenchmarkJsonParserLarge-2                        123830             56023 ns/op               0 B/op          0 allocs/op
BenchmarkJsonParserMedium-2                       617190              9450 ns/op               0 B/op          0 allocs/op
BenchmarkJsonParserDeleteMedium-2                 599527              9954 ns/op               0 B/op          0 allocs/op
BenchmarkJsonParserEachKeyManualMedium-2          990694              6832 ns/op             112 B/op          2 allocs/op …
```
> Updated travis to build for 1.13 to 1.15

- parser.go
Eliminate 2 allocations from EachKey()
```
BenchmarkEachKey
BenchmarkEachKey-8
308006	      3885 ns/op	     272 B/op	       3 allocs/op
PASS
```
```
BenchmarkEachKey
BenchmarkEachKey-8
333666	      3674 ns/op	       8 B/op	       1 allocs/op
PASS
```
Benchmarked with:
```
func BenchmarkEachKey(b *testing.B) {
b.ResetTimer()
for i := 0; i < b.N; i++ {
var id string
var bidId string
var bidImpId string
var bidPrice string
var bidAdm string
var cur string
var foo string
bodyBytes := stringHelper.StringAsBytes(BidResponse_Banner)
jsonparser.EachKey(bodyBytes, func(idx int, value []byte, vt jsonparser.ValueType, err error) {
switch idx {
case 0:
id = stringHelper.BytesAsString(value)
case 1:
bidId = …
```
> - eliminate 2 allocations in EachKey()

- parser.go
- parser_test.go
**Description**: fix issue #150 (in deleting case)
```
BenchmarkJsonParserLarge-8                        149128             40492 ns/op               0 B/op          0 allocs/op
BenchmarkJsonParserMedium-8                       876039              6657 ns/op               0 B/op          0 allocs/op
BenchmarkJsonParserDeleteMedium-8                 823548              7070 ns/op               0 B/op          0 allocs/op
BenchmarkJsonParserEachKeyManualMedium-8         1371667              4380 ns/op             112 B/op          2 allocs/op
BenchmarkJsonParserEachKeyStructMedium
BenchmarkJsonParserEachKeyStructMedium-8         1229190 …
```
> fix deletion by key with leading space

- parser.go
* fixed oss-fuzz issue related to index out of range error (#226)
```
BenchmarkJsonParserLarge-8                        143898             41691 ns/op               0 B/op          0 allocs/op
BenchmarkJsonParserMedium-8                       827924              6878 ns/op               0 B/op          0 allocs/op
BenchmarkJsonParserDeleteMedium-8                 735854              7448 ns/op               0 B/op          0 allocs/op
BenchmarkJsonParserEachKeyManualMedium-8         1309497              4598 ns/op             112 B/op          2 allocs/op
BenchmarkJsonParserEachKeyStructMedium …
```
> fixing the oss-fuzz issue

- bytes.go
- bytes_test.go
**Description**: The current parseInt overflow check may return false negative for input like `27670116110564327410`. This patch fixes the overflow checking.
```
goos: darwin
goarch: amd64
pkg: benchmarks
BenchmarkJsonParserLarge-12                               124323             46955 ns/op               0 B/op          0 allocs/op
BenchmarkJsonParserMedium-12                              771728              7705 ns/op               0 B/op          0 allocs/op
BenchmarkJsonParserDeleteMedium-12                        728377              8323 ns/op               0 B/op          0 allocs/op
BenchmarkJsonParserEachKeyManualMedium-12 …
```
> Fix parseInt overflow check false negative

- parser.go
- parser_test.go
**Description**: This adds a bespoke null error to the typed Get functions
```
BenchmarkJsonParserLarge-4                    	  101186	     59316 ns/op	       0 B/op	       0 allocs/op
BenchmarkJsonParserMedium-4                   	  664688	      9127 ns/op	       0 B/op	       0 allocs/op
BenchmarkJsonParserDeleteMedium-4             	  584113	     16541 ns/op	       0 B/op	       0 allocs/op
BenchmarkJsonParserEachKeyManualMedium-4      	  697446	      7584 ns/op	     112 B/op	       2 allocs/op
BenchmarkJsonParserEachKeyStructMedium
BenchmarkJsonParserEachKeyStructMedium-4      	  718255	      9049 ns/op	     544 B/op	      12 allocs/op …
```
> Added bespoke error for null cases

- parser.go
**Description**: This pr implements patch from #223, which original author never made a PR for. Fixes one allocation in EachKey function caused by allocating pIdxFlags array.
```   
BenchmarkJsonParserEachKeyManualMedium-12         805526              6450 ns/op               8 B/op          2 allocs/op
BenchmarkJsonParserEachKeyStructMedium
BenchmarkJsonParserEachKeyStructMedium-12         644608              9243 ns/op             408 B/op         12 allocs/op
```
```      
BenchmarkJsonParserEachKeyManualMedium-12         947583              6521 ns/op               0 B/op          0 allocs/op
BenchmarkJsonParserEachKeyStructMedium …
```
> fix EachKey pIdxFlags allocation
